### ISSUE TITLE
Possibility of similar identicon collision

### ISSUE THREAD

**Issue by pravj** [cupcake/sigil#3]
Hi there,

It's really nice to see an awesome identicon generator in golang.

My question is that, what's the maximum possible number of identicons sigil can produce?

As I can see that sigil uses 7 colors to fill in tiles and have one options to toggle the colors also.
Methinks that this way, maximum possible identicons will be `(7 * 2) * (2 ** 15)`, as it uses 15 tiles only because of the vertical axis symmetry.

This number is mere `458752` which is too less compared to total number of users on GitHub.

So this way it should be producing similar identicons and collisions are inevitable.

Correct me, if I'm wrong somewhere.

**Comment by titanous** [comment]
The size and number of colors is variable: https://github.com/cupcake/sigil/blob/6bf9722f2ae82f58a0c7d48daeb40ec844b78eae/server.go#L20-L29

I have not done the math recently.
